/**
 * @file src/contracts/mockSendMessageContract.ts
 * Stage 1 Mock Capability Contract: "mock.send_message" (v1.0.0)
 *
 * This contract establishes the exact specifications for schema validation,
 * demonstrating how the locked architectural invariants are declared:
 *
 *  1. Effect Identity != Attempt Identity:
 *     - effect_key represents the unique logical message side effect (e.g. hash of recipient + body + channel).
 *     - cycle_number / attempt_id represents one discrete dispatch cycle.
 *     - execution_identity represents the unique attempt execution boundary (enforced UNIQUE in DB).
 *
 *  2. Correlation Disambiguation:
 *     - client_correlation_id: Control plane generated UUID prior to dispatch; always present.
 *     - provider_dedup_identity: The idempotency key sent to the provider. In SAFE_REPEAT mode,
 *       it remains stable across attempts within the dedup validity window (86400s).
 *     - provider_assigned_id: The external provider's returned ID (e.g. "msg_prov_12345");
 *       nullable, absent until provider successfully responds.
 *
 *  3. SAFE_REPEAT Dedup Window:
 *     - 86,400 seconds (24 hours). Within this window, subsequent cycles may be dispatched even if
 *       the prior attempt is DISPATCHED_UNRESOLVED, because the provider guarantees deduplication.
 *
 *  4. Evidence Attributability:
 *     - Evidence is claim-specific and attributed via CLIENT_CORRELATION_ID_MATCH or PROVIDER_ASSIGNED_ID_LOOKUP.
 */

import { CapabilityContractDefinition } from './types.ts';

export const mockSendMessageContract: CapabilityContractDefinition = {
  capabilityId: 'mock.send_message',
  version: '1.0.0',
  name: 'Mock Message Dispatch Service',
  description: 'Simulated outbound messaging capability with provider-side deduplication guarantees.',
  repeatMode: 'SAFE_REPEAT',
  operationSemantics: 'Idempotent external SMS/chat message dispatch with provider idempotency key header.',
  effectKeyCanonicalizationVersion: 'v1',
  requiredEffectFields: ['recipient', 'message_body', 'channel'],
  providerDedup: {
    semantics: 'PROVIDER_IDEMPOTENCY_KEY',
    identityRule: 'sha256("mock.send_message:v1:" + canonical_payload.recipient + ":" + canonical_payload.channel + ":" + canonical_payload.message_body)',
    validityWindowSeconds: 86400, // 24-hour guarantee from external provider
  },
  supportedEvidenceTypes: [
    'EXECUTION_CONFIRMED',
    'NON_EXECUTION_CONFIRMED',
    'PROVIDER_REJECTED',
    'PROVIDER_TIMEOUT',
    'UNKNOWN_DISPATCH_FAILURE',
    'RECONCILIATION_REPORT',
  ],
  evidenceCorrelationMethod: 'CLIENT_CORRELATION_ID_MATCH',
  heartbeatIntervalSeconds: 60,
  reconciliation: {
    pollIntervalSeconds: 300,
    maxUnresolvedDurationSeconds: 600,
    reconciliationEndpointOrMethod: 'GET /v1/messages/query_by_correlation',
    supportsStatusQueryByCorrelationId: true,
    supportsStatusQueryByProviderAssignedId: true,
  },
  correlationRules: {
    effectVsAttemptExplanation:
      'effect_key identifies the real-world side effect (e.g. delivering message M to recipient R). ' +
      'Multiple intents may converge on this same effect_key. ' +
      'Each dispatch attempt receives a distinct attempt_id and cycle_number.',
    clientCorrelationExplanation:
      'client_correlation_id is a fresh UUID generated by the control plane for every attempt before dispatch. ' +
      'It identifies this exact dispatch invocation.',
    providerDedupExplanation:
      'provider_dedup_identity is derived deterministically from the canonical effect payload. ' +
      'Under SAFE_REPEAT, it remains identical across retry cycles to trigger provider-side deduplication.',
    providerAssignedIdExplanation:
      'provider_assigned_id is NULL when an attempt is RESERVED or DISPATCHED_UNRESOLVED, ' +
      'and is populated only if and when the provider returns a downstream receipt ID.',
  },
};

export const mockSendMessageUnsafeContract: CapabilityContractDefinition = {
  capabilityId: 'mock.send_message_unsafe',
  version: '1.0.0',
  name: 'Mock Unsafe Message Dispatch Service',
  description: 'Simulated non-deduplicating messaging capability requiring strict terminal confirmation before repeat.',
  repeatMode: 'UNSAFE_REPEAT',
  operationSemantics: 'External message dispatch without provider deduplication; retries risk duplicate real-world effects.',
  effectKeyCanonicalizationVersion: 'v1',
  requiredEffectFields: ['recipient', 'message_body', 'channel'],
  providerDedup: {
    semantics: 'NONE',
    identityRule: 'none',
    validityWindowSeconds: null,
  },
  supportedEvidenceTypes: [
    'EXECUTION_CONFIRMED',
    'NON_EXECUTION_CONFIRMED',
    'PROVIDER_REJECTED',
    'PROVIDER_TIMEOUT',
    'UNKNOWN_DISPATCH_FAILURE',
    'RECONCILIATION_REPORT',
  ],
  evidenceCorrelationMethod: 'CLIENT_CORRELATION_ID_MATCH',
  heartbeatIntervalSeconds: 60,
  reconciliation: {
    pollIntervalSeconds: 300,
    maxUnresolvedDurationSeconds: 600,
    reconciliationEndpointOrMethod: 'GET /v1/messages/query_by_correlation',
    supportsStatusQueryByCorrelationId: true,
    supportsStatusQueryByProviderAssignedId: true,
  },
  correlationRules: {
    effectVsAttemptExplanation:
      'In UNSAFE_REPEAT, effect_key represents the single logical side effect. ' +
      'No secondary dispatch cycle may be authorized while any previous attempt is unresolved.',
    clientCorrelationExplanation:
      'client_correlation_id uniquely correlates each dispatch attempt.',
    providerDedupExplanation:
      'No provider deduplication is provided in UNSAFE_REPEAT.',
    providerAssignedIdExplanation:
      'provider_assigned_id is populated only after provider acknowledges receipt.',
  },
};

